version: '3'

services:
  activemq:
    image: webcenter/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161" # web admin console port
      - "61616:61616" # broker port


# KULLANICI ADI - ÅÄ°FRE => admin-admin